# helm repo add ra https://rasla.github.io/charts ; helm repo update
# helm search repo echo
# helm upgrade --install echo ra/echo -n echo -f config-echo.local.yaml --version 0.1.0

replicaCount: 1

service:
  port: 8080

ingress:
  enabled: false
  className: "nginx"
  hosts:
    - host: k8s.n.rasla.ru
      paths:
        - path: /test1(/|$)(.*)
          pathType: Prefix
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$2  # /api/$2

resources:
   requests:
     cpu: 10m
     memory: 32Mi
