# Example values for HELM-charts 'au/ksvd', 'au/pdc' and 'au/tsdb'

au_tsdb:
  monitoringEnabled: true

au_tsdb_storage:
  dbStorage: 'clickhouse'  #  all / clickhouse / influxdb
  dbUsername: 'root'
  dbPassword: '123123123'
  clickhouseImageTag: '20.3.11.97'  # LTS: 20.3.11.97
  clickhousePortData: 8123
  influxdbImageTag: '1.8.0-alpine'
  influxdbPortData: 8086
  monitoringEnabled: true

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
